language: python
dist: bionic
sudo: false

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

before-install:
    - "pip install -U numpy"

install:

script:
    - "python polygon_inclusion.py"
